apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      name: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: rabbitmq-secrets
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: rabbitmq-secrets
