apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    name: rabbitmq
  ports:
  - name: rabbitmq-service
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: rabbitmq-api
    protocol: TCP
    port: 15672
    targetPort: 15672